### ISSUE TITLE
relevanssi_new_blog not added to action and never runs

### ISSUE THREAD

**Issue by oxyc** [msaari/relevanssi#17]
It seems like `relevanssi_new_blog()` hasnt been added to either the `wp_insert_site` or the `wpmu_new_blog` actions and thus never runs on new blogs.

**Comment by msaari** [comment]
It's added in Relevanssi Premium... but yeah, good catch, it was missing from the free version. Next version will add it, here's the commit: https://github.com/msaari/relevanssi/commit/c8f90ba306b5397361676c24f3a7b56608370304
