### ISSUE TITLE
Does `relevanssi_words` option need to be autoloaded?

### ISSUE THREAD

**Issue by lkraav** [msaari/relevanssi#19]
Hi. Doing an options table performance analysis with https://kinsta.com/knowledgebase/wp-options-autoloaded-data/ I've discovered that `relevanssi_words` is now the top sized (120 kB) option.

Is it required to autoload on every request, or could Relevanssi load it only within its usage context?

**Comment by msaari** [comment]
No, it doesn't need to  be autoloaded, and it's already fixed for Premium 2.8.0.

**Comment by lkraav** [comment]
@msaari I'm now noticing 2.8.0 hasn't been released yet. Wondering if I should just hand-mod the autoload status of this row or wait for the release?

**Comment by msaari** [comment]
2.8.0 is finished and is currently in testing; I'm just having some problems with Composer, otherwise I would've released it already... So it's coming soon.

**Comment by lkraav** [comment]
Updated to 2.8.0 today, but `relevanssi_words` is still showing up autoloaded in the database alert query.

I updated via `wp plugin update`, also tested "Save the options" button Relevanssi admin page, but nothing changes.

Changelog doesn't mention any manual action being needed, so wondering if this is a bug or what the process is getting this row updated?

**Comment by msaari** [comment]
There's no action to make it not autoload, but when it expires and the new option is created, it's no longer autoloaded. You can manually adjust the current option in the database table if you want the change to take effect immediately.
