### ISSUE TITLE
Dashboard item searches show no results

### ISSUE THREAD

**Issue by tleen** [msaari/relevanssi#2]
@msaari I thought it would be good to mention this here in case people were looking for the issue and were able to fix it by disabling relevanssi.

It is a conflict with the Yoast Seo Plugin v5.0.2, a working temporary fix would be to downgrade to v5.0.1. The issue is already open @ Yoast/wordpress-seo#7480

**Comment by msaari** [comment]
The problem happens with 5.0.1 as well – I remember upgrading to 5.0.2 to see if the problem goes away, and it didn't.

**Comment by tleen** [comment]
Hm.Now that I look at it you are right. I had a mess of trouble trying to downgrade on some sites the SEO plugin did not like it and refused to activate.

**Comment by msaari** [comment]
This problem can be solved by disabling "Text link counter" in Yoast SEO settings.

**Comment by msaari** [comment]
This problem was finally solved by Yoast SEO 11.8.
