### ISSUE TITLE
analyze table suggestion

### ISSUE THREAD

**Issue by asakous** [msaari/relevanssi#25]
when relevanssi table has millions recode. analyze table will become slower and slower . especially on rebuild whole posts. 
maybe just move the command right before complete ?

       // To prevent empty indices.
	$wpdb->query( "ANALYZE TABLE $relevanssi_table" ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared,WordPress.DB.PreparedSQL.InterpolatedNotPrepared

	$complete = false;
	$size     = $indexing_query_args['size'];

	if ( ( 0 === $size ) || ( count( $content ) < $size ) ) {
		$complete = true;
		$wpdb->query( "ANALYZE TABLE $relevanssi_table" );--> move to here 
		update_option( 'relevanssi_indexed', 'done', false );

		// Update the document count variable.
		relevanssi_async_update_doc_count();
	}

**Comment by msaari** [comment]
Yes, this makes perfect sense. I'll implement this.
