### ISSUE TITLE
redundant index docs

### ISSUE THREAD

**Issue by asakous** [msaari/relevanssi#27]
since primary key already cover up doc column, threre is no need to create a independent for doc column. 
for example
explain select * from wp_relevanssi where doc=12344
result 
1 | SIMPLE | wp_relevanssi | ref | PRIMARY,docs | **PRIMARY** | 4 | const | 1 |  

mysql use key PRIMARY, not key doc

**Comment by msaari** [comment]
I checked this with the actual search queries done by Relevanssi and looks like you're correct, that index is redundant. I'll remove this in the next version.

Thanks!
