### ISSUE TITLE
v3.6

### ISSUE THREAD

**Issue by tleen** [msaari/relevanssi#3]
@msaari can you tag the v3.6 release? I think it caused an issue and I would like to compare to see what happened.

**Comment by msaari** [comment]
Sure. It's quite possible it did cause an issue, as it changed how Relevanssi attaches itself to queries. In earlier versions, Relevanssi uses the_posts hook, but uses the global $wp_query object. In 3.6.0, it's still the_posts, but Relevanssi uses the query object passed as a parameter to the_posts.

I know this causes issues with Search & Filter Pro, for example.

**Comment by tleen** [comment]
Yep it did something to prevent my search but I'll figure it out. Thanks!
