### ISSUE TITLE
Search logs adds

### ISSUE THREAD

**Issue by janw-me** [msaari/relevanssi#30]
When a synonym is found it is included in the search log.
reproduce:

1) Create synonym:  round = circle.
2) Enable logging
3) Do a search for "round"
4) Export csv log (or check DB)
5) See "round circle" in the log.

I have found where to fix this, but I can see several approaches and there are probably more.

a) Don't log the synonym word
b) Do log the synonym but mark it in some way:  round (synonym:circle)
c) Add a new column to the log table and log it seperatly.
d) ...?

I'm willing to work on this, but I'd like to discuss the best way to do this before starting.

**Comment by msaari** [comment]
That's a good question and I'm not sure what would be the best option.

I'm reluctant to making changes in the database structure, and I don't like the extra markup, as that requires further changes in the User Searches page where the queries are used, so I suppose it's either

a) Log the query with the synonyms
b) Log the original query without the synonyms

I could see this go both ways, maybe with a filter hook to toggle it? I suppose not logging the synonym might make more sense as the default value. Any thoughts on that?

**Comment by msaari** [comment]
I went with no synonyms, and a filter hook to change that. See a37a8c97c50a50f1b357c411673f3780b38e4e4a.

**Comment by janw-me** [comment]
I agree with your conclusion of not logging synonyms, but I've added a way to make the content flexible.
Also php version.
This can live on in [pull#31](https://github.com/msaari/relevanssi/pull/31)
