### ISSUE TITLE
Issue when Relevanssi is used with Oxygen Builder AND ACF

### ISSUE THREAD

**Issue by alleykatwc** [msaari/relevanssi#32]
It seems there may be a slight bug in Relevanssi since the incorporation of Oxygen Builder.  When using ACF and Oxygen Builder, the custom fields for ACF are not indexed.  You also are unable to change the custom fields drop-down in Relevansi to anything other than some (which looks to pre-populate the field with "ct_builder_shortcodes". 

When you disable oxygen builder, you're able to change the fields ^^ and Relevanssi will index ACF fields, once you turn oxygen builder back on, the same actions happen (but if you don't rebuild your index it works.

Any chance to rectify this bug so that ACF and Oxygen builder can function and be indexed when both are in use?

**Comment by msaari** [comment]
This is a known issue and is already fixed here: 13a0b3e814a446c57e9a0eb04e6bda34903e9ad0.

This will be included in the next version, but meanwhile you can just grab the updated oxygen.php file.
