### ISSUE TITLE
Using search result highlighting breaks <code>-blocks

### ISSUE THREAD

**Issue by koskila** [msaari/relevanssi#42]
Hi there - first of all, thanks for an immensely helpful plug-in. Love it.

That said, I have a small bug to report. Not sure if this really is Relevanssi's doing, but I think so.

**Problem**
Whenever "highlight in documents" is enabled, any code blocks on the page break (<pre><code> is not parsed properly). 

With this configuration:
![image](https://user-images.githubusercontent.com/4086860/131980196-d0642778-008f-4fb2-90fc-f4d5e9c3e510.png)

A page with "highlight" in URL will look like this:
![image](https://user-images.githubusercontent.com/4086860/131980243-0e3a91b1-733c-4659-bda1-7bc19680c934.png)

Whenever either highlighting is disabled or the URL parameter removed, it works properly:
![image](https://user-images.githubusercontent.com/4086860/131980292-ec2d1592-a553-4124-bdd1-fee7fa2a1465.png)

Any thoughts?

**Comment by msaari** [comment]
Yes, it's Relevanssi and no, it's not a bug, it's a feature. Or to be more exact: just a side-effect of things that cannot really be avoided.

There are two ways to deal with this: use the `relevanssi_entities_inside_code` filter hook ([see documentation](https://www.relevanssi.com/user-manual/filter-hooks/relevanssi_entities_inside_tag/)) to change the Relevanssi behaviour, or just remove the `code` blocks from the excerpts ([see documentation](https://www.relevanssi.com/knowledge-base/blocking-pre-and-code-tags/)).

**Comment by koskila** [comment]
Thanks for the quick response and explanation! I was trying to add the filters, but they were only a partial fix:

add_filter( 'relevanssi_entities_inside_code', '__return_false' );
add_filter( 'relevanssi_entities_inside_pre', '__return_false' );

The block is now only partially broken:
![image](https://user-images.githubusercontent.com/4086860/131988046-48be24de-7918-4a76-a800-0711e3e31bb5.png)

Is this expected or am I messing something up?

**Comment by msaari** [comment]
Actually, this is a separate issue. When you set this filters to `false`, the entity handling is fine – but the whitespace is still messed up. The problem isn't specific to `code` or `pre` tags, but to all significant whitespace. It's because Relevanssi does this:

`$content = str_replace( "\n", ' ', $content );`

If that is changed to this:

`if ( ! $convert_entities ) {
	$content = str_replace( "\n", ' ', $content );
}`

Then the linefeeds are kept in place in post content, and the code looks much better.

**Comment by msaari** [comment]
See https://github.com/msaari/relevanssi/commit/e7aa9073196117a0097fa4b84982b6843914ccd1

**Comment by koskila** [comment]
Nice, that was fast 👍

If it builds (and I'm sure it will), ship it? 😉

**Comment by msaari** [comment]
Well, I already commited it to the plugin codebase, so yeah, consider it shipped.
