### ISSUE TITLE
Bug: Highlighting causing broken HTML

### ISSUE THREAD

**Issue by Faeddur** [msaari/relevanssi#49]
First of all, thanks for the great plugin!

We found a bug, which is causing the HTML to be invalid when highlighting - data-attributes are catched incorrectly by the regular expression.

We've got these "Search hit highlighting" settings:

- Highlight type: CSS class
- CSS class for highlights: search-results__term-hint
- Highlight in titles: true
- Highlight in documents: true
- Highlight in comments: false
- Expand highlights: false

In our theme we tend to use data-attributes without values to create bindings for JavaScript, like so:

```html
<a
	data-tile
	data-tile-type="file"
>
	<p data-tile-file-heading>...</p>
	<p data-tile-file-filesize-and-ext>pdf</p>
</a>
```

Given the settings, if you go to the page with that HTML and add the highlight URL param at the end (`?highlight=string`), this HTML will be converted to this form:

```html
<a
	data-tile
	data-tile-type="file&quot;
&gt;
	&lt;p data-tile-file-heading&gt;&hellip;&lt;/p&gt;
	&lt;p data-tile-file-filesize-and-ext&gt;pdf&lt;/p&gt;
&lt;/a&gt;
```

Which is of course invalid.

This is a problem with not so perfect regular expression found here:

https://github.com/msaari/relevanssi/blob/c72c448a7a1d4f8d020e8a9f546144721f82d878/lib/excerpts-highlights.php#L1569

This regular expression does better at job:

```php
if ( preg_match_all( '/data-[\w-]+?="([^"]*?)"/sm', $content, $matches ) ) {}
```

**Comment by msaari** [comment]
Thanks, this was already improved from the abysmal first take in the latest version. Hopefully, this update will make it work reliably.

**Comment by Faeddur** [comment]
Thanks for the quick response) your plugin gets better and better with each release)
