### ISSUE TITLE
Duplicate Searches logged if using inline 'background-image:url();'

### ISSUE THREAD

**Issue by theaemarie** [msaari/relevanssi#5]
It seems that if you have an inline background-image rendered to your template, (with no image present), then searches get logged twice.

**Steps to reproduce:**
1. Clean install of Wordpress
1. Install Relevanssi
1. Check 'Keep a log of user queries'
1. Use 2017 theme.
1. In `template-parts/post/content-excerpt.php`, add the line `<div style="background-image:url();"></div>` so it will appear on the rendered page
1. Search for 'world'
1. The 'search count' will increase by two.

**Fun Fact:**
1. Edit the line of HTML that you added to have a image: `<div style="background-image:url(http:image.com);"></div>`
1. Search for 'world'
1. Search count only increases by one.

This seems like it might even be a WordPress problem, but I wanted to make a mention of it here first as it is counting the logs in a Relevanssi created table.

**Comment by msaari** [comment]
Hi, this isn't really a bug in Relevanssi or in WordPress, just some unusual and unexpected behaviour from your browser.

What happens here is that when you specify an empty URL, the browser uses the current page URL. (You can see similar behaviour when you create a link with an empty HREF: it points to the current page.) On a search page, that causes a repeated search. So, you're essentially loading the search page twice.

This is an old thing; [here's an article about it from 2009](https://www.nczonline.net/blog/2009/11/30/empty-image-src-can-destroy-your-site/).

The solution is to make sure the image URL is never empty.

**Comment by theaemarie** [comment]
Ahhh. That makes so much sense!

And yeah, I just put a check before I rendered that out.

Thanks!
