### ISSUE TITLE
Relevanssi Premium, relevanssi_do_query returns stdClasses

### ISSUE THREAD

**Issue by JorenRothman** [msaari/relevanssi#51]
Come across this bug today, 

If you use a WP_Query in combination with the relevanssi_do_query function the resulting items will be a object of the type stdClass instead of the type WP_post. 

This bug only happens in the premium version, the free version behaves like expected.

Premium version: 2.23.0
Free version: 4.20.0
PHP: 8.0

**Example code**
```php
 $args = [
            's' => $query,
            'post_type' => isset($_GET['view']) && $_GET['view'] === 'product' ? 'product' : 'any',
            'post_status' => 'publish',
            'posts_per_page' => -1,
            'orderby' => 'date',
            'order' => 'DESC',
        ];

        $query = new \WP_Query();
        $query->parse_query($args);

        $items = relevanssi_do_query($query);
```
**Expected:** $items should be an array of WP_Post objects (if there are results)
**Result:** $items is an array of stdClass

**Comment by msaari** [comment]
It's not a bug; it's a feature.

In the free version of Relevanssi, the search can only return posts, which are returned as WP_Post objects. Relevanssi Premium should also return posts as WP_Post objects but can also return taxonomy terms, user profiles and post type archives. Those are stdClass objects that look like WP_Post objects. They cannot be WP_Post objects as they're not posts.

Are you getting actual posts as stdClass objects? That should not happen with Relevanssi Premium.

**Comment by msaari** [comment]
Ah, I see. If you use `relevanssi_do_query()` like that, you do get stdClass objects. The answer is: don't do it like that, use the preferred method of:

` $args = [
            's' => $query,
            'post_type' => isset($_GET['view']) && $_GET['view'] === 'product' ? 'product' : 'any',
            'post_status' => 'publish',
            'posts_per_page' => -1,
            'orderby' => 'date',
            'order' => 'DESC',
            'relevanssi' => true,
        ];

        $query = new \WP_Query($args);
`

This will get you WP_Post objects. I'll have to see why calling `relevanssi_do_query()` returns stdClass objects, but in general, calling the function directly is no longer the recommended approach (I know there are lots of instructions floating around that tell you to do that, but they're outdated).

**Comment by JorenRothman** [comment]
@msaari Thanks for the response, closing the issue.
