### ISSUE TITLE
relevanssi_render_block not called

### ISSUE THREAD

**Issue by flavh** [msaari/relevanssi#52]
Hello,

I'm trying to exclude some Gutenberg blocks from Relevanssi indexing by adding a filter with the following code :
```php
add_filter('relevanssi_render_block', 'exclude_block_from_search_render');

function exclude_block_from_search_render($block) {
	error_log('TEST RENDER_BLOCK');
}
```

The problem is that this function is never called during searches. I've also tried the "relevanssi_hits_filter" filter, which is called, but that's not the one I need.

Is this a premium feature? If not, how can I correct this error?

Thanks for your help

**Comment by msaari** [comment]
It's not a premium feature. The reason it's not called during searches is because it's an indexing hook: it only happens when the post is indexed. Try saving the post: that should trigger the function.
