### ISSUE TITLE
Exact match boost not working with capital accented letters

### ISSUE THREAD

**Issue by Jaessun** [msaari/relevanssi#53]
Hi,

I've recently had an issue with the exact match boost setting not working properly in some cases, and after digging in the code I believe I found the issue.

Basically, to apply the exact match boost the search query is matched against the post title using `stristr()` :

https://github.com/msaari/relevanssi/blob/58391b53e976094308fbce6e88ba5ce77fe4f769/lib/search.php#L1433-L1438

However when using capital accented letters, they are not properly converted into lowercase by that function. For example, this will return false : `stristr( 'CAFÉ', 'café' )`.

I believe using `mb_stristr()` instead of `stristr()` would fix this.

**Comment by msaari** [comment]
Thanks, that sounds reasonable. I'll look into this.

**Comment by msaari** [comment]
Sorry, I missed this in 4.21.0. This will be fixed in the next version.
