### ISSUE TITLE
Homepage displaying unwanted search results

### ISSUE THREAD

**Issue by cchiera-od** [msaari/relevanssi#56]
If I type in the homepage address plus “/?posts_per_page=83” I am getting results and it is saving it in google search. If I turn off “Relevanssi” it does not display these results. I want it to NOT display results and also ignore any kind of indexing by google if I type in “myhomepageurl/?posts_per_page=83”. How do I disable this feature but keep the plugin at the same time?
Thanks

**Comment by msaari** [comment]
Which theme? That's important here. In Twenty Twenty-Four, for example, this just changes the number of posts displayed in the front page post list, which is the expected behaviour.
