### ISSUE TITLE
Bug: Pagination prev/next mixed up

### ISSUE THREAD

**Issue by ur-krostitzer** [msaari/relevanssi#60]
Hi,

I've noticed a minor bug when search results return more than one page. On the bottom of the page there is only a "previous" link. When clicking the link it takes me to page 2. When on page 2 I can click on "next" which takes me back to page 1.

Also btw. is there an infinite scrolling option? Could not find one in settings.

**Comment by msaari** [comment]
Infinite scrolling is out of scope. It's up to the theme. You can use infinite scrolling with Relevanssi, as long as you use the Relevanssi query. Some infinite scrolling methods create a new query that doesn't invoke Relevanssi.

The next and previous links are also coming from your theme. Relevanssi doesn't provide them.

**Comment by ur-krostitzer** [comment]
Alright, then I guess you can mark that as closed
