### ISSUE TITLE
Divi implementation does not work

### ISSUE THREAD

**Issue by cagno0di** [msaari/relevanssi#62]
Unfortunately, the search function does not work in conjunction with Divi. Even after following the instructions of the PHP script from the Docs.

**Comment by msaari** [comment]
This is not the place for user support. Please use the WordPress.org support forums or the Premium support if you have a Premium license.

Relevanssi and Divi should have no general compatibility problems, and in most cases, they should work fine without any PHP scripts. This is something about your specific site setup, and I can help you dig deeper in the proper support channels.
