### ISSUE TITLE
Bug: install error with Polylang

### ISSUE THREAD

**Issue by mateofaivre** [msaari/relevanssi#63]
Hi,

I have Polylang Pro 3.6.5.
When I try for the first time to install and activate Relevanssi, it causes a fatal error : 
Call to undefined function relevanssi_get_language_term_taxonomy_id() in plugins/relevanssi/lib/stopwords.php:246
No problem if i activate Relevanssi without Polylang.

Can you take a look at this please ?
Thanks

**Comment by msaari** [comment]
I know why the error happens, but I don't see how those circumstances can occur.

When you install Relevanssi, it creates the database tables and fetches the default stopwords if there are no stopwords. When Polylang is active, this involves the `relevanssi_get_language_term_taxonomy_id()` function. This function is defined in the Relevanssi Polylang compatibility code, but for some reason, in your case, the compatibility code doesn't run.

It shouldn't be about timing: the compatibility code is activated in `init`, and the stopword fetching is done in `admin_init`, which happens after `init`. 

Anyway, I see I can reproduce this issue, so I'll look and see what's causing this. Meanwhile, the simple fix is to deactivate Polylang, activate Relevanssi, activate Polylang and then in Relevanssi stopword settings, click "Add default stopwords" for all languages.
