### ISSUE TITLE
PHP Warning:  preg_match(): Null byte in regex

### ISSUE THREAD

**Issue by tomdxw** [msaari/relevanssi#7]
The use of `stripslashes` causes NULL bytes to appear in text. When this text is fed into `preg_match` it causes warnings. Example:

```
Mar 14 16:59:10 ip-10-36-94-105 apache2[6306]: PHP Warning:  preg_match(): Null byte in regex in /.../wp-content/plugins/relevanssi-premium/lib/excerpts-highlights.php on line 525
Mar 14 16:59:10 ip-10-36-94-105 apache2[6306]: PHP Warning:  preg_match(): Null byte in regex in /.../wp-content/plugins/relevanssi-premium/lib/excerpts-highlights.php on line 529
```

I wasn't able to reproduce the warnings, but I was able to show that null bytes get added (in both `relevanssi` and `relevanssi-premium`). Steps to reproduce:

- Activate `relevanssi` (or `relevanssi-premium`)
- Edit `lib/common.php`: Add `echo json_encode($string);` after this line: `function relevanssi_tokenize( $string, $remove_stops = true, $min_word_length = -1 ) {`
- Search for `hello\\0world`: i.e. `http://localhost/?s=hello%5C%5C0world`
- `"hello\\0world""hello\u0000world"` will appear on the page. `\u0000` is the JSON-encoded NULL byte. In some circumstances this string is passed to `preg_match`, which causes warnings.

This happens because the `stripslashes` function not only strips slashes, it also replaces `\0` with a NULL byte. This feature is undocumented, you can see it here in PHP's source: https://github.com/php/php-src/blob/php-7.2.3/ext/standard/string.c#L3616-L3651

**Comment by msaari** [comment]
Thanks. Which version of Relevanssi? What is on the lines 525 and 529? In the current version those lines don't really match anything that would fit.

I'm also slightly puzzled by those error messages, as there are no `preg_match()` calls in the file, just couple cases of `preg_match_all()`. In the `preg_match_all()` calls around the line 520, the regexes are fixed, and do not contain null bytes.

So all in all a strange case, but it's not a big deal to make `relevanssi_mb_trim()` remove null bytes from strings. Since `relevanssi_tokenize()` passes all tokens through the trim, that should fix this issue. Do you agree?

**Comment by tomdxw** [comment]
Those logs come from the premium version at 1.16.0.1:

```
                        $pattern = '/([\s,\.:;\?!\']'.$word.')/i';
                        if (preg_match($pattern, $fulltext, $matches, PREG_OFFSET_CAPTURE)) {
                                $count += count($matches) - 1;
                        }
                        $pattern = '/('.$word.'[\s,\.:;\?!\'])/i';
                        if (preg_match($pattern, $fulltext, $matches, PREG_OFFSET_CAPTURE)) {
                                $count += count($matches) - 1;
                        }
```

I suppose these lines aren't in the free version, but both versions end up with strings containing NULL bytes.

> Since relevanssi_tokenize() passes all tokens through the trim, that should fix this issue. Do you agree?

I think so, yes. Thank you.

**Comment by msaari** [comment]
The current version of Premium is 2.1.3, and doesn't have that bit of code at all. The current code is the same as in the free version now. So, it may have null bytes in string, but the error message won't happen.

**Comment by tomdxw** [comment]
Apologies. I should have checked our version was the latest. Thank you for your help!
